deploy:
on push

- name: SCP Deployment
  # You may pin to the exact commit or the version.
  # uses: srueda99/scp-action@b8768ecdd6dd99c8c65501677b75c3b70c94da82
  uses: srueda99/scp-action@v12
  with:
    # Port for SCP
    port: 22
    # IP Address or DNS of your target host
    host: # optional
    # Source route folder
    origin: # optional, default is ./*
    # Destination route folder
    destination: # optional
    # User for remote connection
    username: # optional
    # Password for the user
    password: # optional
    # Private SSH key
    key: # optional
    # Passphrase for SSH key
    passphrase: # optional
